name: CI

# Alterar depois pra branch main
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Config GitHub
        run: |
          git config --global user.email "${{secrets.GIT_USER_EMAIL}}"
          git config --global user.name "${{secrets.GIT_USER_NAME}}"
  
      # NPM AUDIT
      # - name: run npm audit
      #   uses: oke-py/npm-audit-action@v2
      #   with:
      #     audit_level: low
      #     create_issues: true
      #     github_token: ${{ secrets.TOKEN_GIT }}
      #     issue_labels: vulnerability

      - name: install dependencies
        run: sudo docker-compose build

      # SonarCloud Scan
      - name: SonarCloud
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 
      
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GIT }} 
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      
      - name: Checkout Repository
        uses: actions/checkout@v2

      #Ferramentas SCA

      # OWASP DEPENDENCY CHECK (63 estrelas)
      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        with:
          project: 'tcc-password-manager'
          path: './'
          format: 'HTML'
          out: 'reports'
          args: >
            --failOnCVSS 7
            --enableRetired

      - name: Upload Test results
        uses: actions/upload-artifact@v4
        with:
           name: Depcheck report
           path:  ${{github.workspace}}/reports

      - name: Save Results
        if: always()
        run: |
          git clone "https://x-access-token:${{secrets.TOKEN_GIT}}@github.com/tcc-lucas-dafne/${{secrets.NAME_REPO_GIT}}" ${{secrets.NAME_REPO_GIT}}
          mkdir -p ${{secrets.NAME_REPO_GIT}}/reports
          cp -R ${{github.workspace}}/reports ${{secrets.NAME_REPO_GIT}}/reports
          cd ${{secrets.NAME_REPO_GIT}}
          git add .
          git commit -m "Adicionando relatório no repositório ${{ github.event.repository.name }} ${{ github.ref_name }}"
          git push