name: SCA Tests

on:
  pull_request:
    branches: [develop]

jobs:
  sca_depcheck:
    name: 'Owasp Dependency Check'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Config GitHub
        run: |
          git config --global user.email "${{secrets.GIT_USER_EMAIL}}"
          git config --global user.name "${{secrets.GIT_USER_NAME}}"

      - name: install npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.TOKEN_GIT }}
        run: npm ci

      # SCA
      
      # SNYK
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif

      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk.sarif
          category: my-analysis-tool
      
      # OWASP DEPENDENCY CHECK
      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        with:
          project: 'tcc-password-manager'
          path: './'
          format: 'HTML'
          out: '.'
          args: >
            # --failOnCVSS 7
            --enableRetired

      - name: Check
        run: ls

      - name: Upload Test results
        uses: actions/upload-artifact@v4
        with:
           name: Depcheck report
           path:  ${{github.workspace}}
      
